<?php
namespace App\Models\Enum;


interface NotificationTypes
{
    const JOIN_ACTIVITY = "JOIN_ACTIVITY";
    const INVITE_TO_ACTIVITY = "INVITE_TO_ACTIVITY";
    const ACTIVITY_UPDATED = "ACTIVITY_UPDATED";
    const DECLINE_ACTIVITY_INVITATION = "DECLINE_ACTIVITY_INVITATION";
    const CANCEL_ACTIVITY = "CANCEL_ACTIVITY";
    const CONNECTION_REQUEST_RECEIVED = 'CONNECTION_REQUEST_RECEIVED';
}