<?php

/*
|--------------------------------------------------------------------------
| Model Factories
|--------------------------------------------------------------------------
|
| Here you may define all of your model factories. Model factories give
| you a convenient way to create models for testing and seeding your
| database. Just tell the factory how a default model should look.
|
*/

$factory->define(App\Models\Eloquent\User\User::class, function (Faker\Generator $faker) {

    $countries = [
        'Abkhazia',
        'Afghanistan',
        'Albania',
        'Algeria',
        'Andorra',
        'Angola',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas, The',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Benin',
        'Bhutan',
        'Bolivia',
        'Bosnia and Herzegovina',
        'Botswana',
        'Brazil',
        'Brunei',
        'Bulgaria',
        'Burkina Faso',
        'Burma',
        'Burundi',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Cape Verde',
        'Central African Republic',
        'Chad',
        'Chile',
        'China',
        'Colombia',
        'Comoros',
        'Congo, Democratic Republic of the',
        'Congo, Republic of the',
        'Cook Islands',
        'Costa Rica',
        'Croatia',
        'Cuba',
        'Cyprus',
        'Czech Republic',
        'Denmark',
        'Djibouti',
        'Dominica',
        'Dominican Republic',
        'East Timor',
        'Ecuador',
        'Egypt',
        'El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Ethiopia',
        'Fiji',
        'Finland',
        'France',
        'Gabon',
        'Gambia, The',
        'Georgia',
        'Germany',
        'Ghana',
        'Greece',
        'Grenada',
        'Guatemala',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Honduras',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Israel',
        'Italy',
        'Ivory Coast',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        'Korea, North',
        'Korea, South',
        'Kosovo',
        'Kuwait',
        'Kyrgyzstan',
        'Laos',
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Macedonia',
        'Madagascar',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Mali',
        'Malta',
        'Marshall Islands',
        'Mauritania',
        'Mauritius',
        'Mexico',
        'Micronesia',
        'Moldova',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Morocco',
        'Mozambique',
        'Nagorno-Karabakh',
        'Namibia',
        'Nauru',
        'Nepal',
        'Netherlands',
        'New Zealand',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'Niue',
        'Northern Cyprus',
        'Norway',
        'Oman',
        'Pakistan',
        'Palau',
        'Palestine',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Qatar',
        'Romania',
        'Russia',
        'Rwanda',
        'Sahrawi Arab Democratic Republic',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Samoa',
        'San Marino',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leone',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'Solomon Islands',
        'Somalia',
        'Somaliland',
        'South Africa',
        'South Ossetia',
        'South Sudan',
        'Spain',
        'Sri Lanka',
        'Sudan',
        'Suriname',
        'Swaziland',
        'Sweden',
        'Switzerland',
        'Syria',
        'São Tomé and Príncipe',
        'Taiwan',
        'Tajikistan',
        'Tanzania',
        'Thailand',
        'Togo',
        'Tonga',
        'Transnistria',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Tuvalu',
        'Uganda',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Vatican City',
        'Venezuela',
        'Vietnam',
        'Yemen',
        'Zambia',
        'Zimbabwe',
    ];

    $shirtnames = [
        'The Terminator',
        'Batman',
        'Spiderman',
        'Superman',
        'Twinky',
        'Rockstar',
        'Longbeard',
        'The Pirate',
        'Rudolph the Rednosed Reindeer',
        'Bad Santa',
        'Captain Jack Sparrow',
        'Pothead',
        'The Dude'
    ];

    $quotes = [
        'Only he who can see the invisible can do the impossible.',
        'A trophy carries dust. Memories last forever.',
        'Set your goals high, and don\'t stop till you get there.',
        'If you can\'t outplay them, outwork them.',
        'Good is not good when better is expected.',
        'Champions keep playing until they get it right.',
        'If you fail to prepare, you\'re prepared to fail.',
        'The road to Easy Street goes through the sewer.',
        'Nobody who ever gave his best regretted it.',
        'When you win, say nothing, when you lose, say less.',
        'If you can believe it, the mind can achieve it.',
        'Without self-discipline, success is impossible, period.',
        'Make each day your masterpiece.',
        'Win If You Can, Lose If You Must, But NEVER QUIT!',
        'Just keep going. Everybody gets better if they keep at it.',
        'If you aren\'t going all the way, why go at all?',
        'Wisdom is always an overmatch for strength.',
        'Adversity cause some men to break; others to break records.',
        'Never let the fear of striking out get in your way.',
        'A champion is someone who gets up when he can’t.',
        'It ain\'t over till it\'s over.',
        'You\'re never a loser until you quit trying.',
        'You miss 100 percent of the shots you don\'t take.'
    ];

    return [
        'first_name'      => $fName = $faker->unique()->firstName,
        'last_name'       => $lName = $faker->lastName,
        'birthday'        => $faker->date('Y-m-d', '13 years ago'),
        'email'           => mb_strtolower($faker->email, 'UTF-8'),
        'username'        => mb_strtolower($fName . '.' . $lName, 'UTF-8'),
        'password'        => 'supersecret',
        'shirtname'       => $faker->randomElement($shirtnames),
        'gender'          => $faker->randomElement(['male', 'female', 'transgender']),
        'about_me'        => $faker->text(200),
        'sportquote'      => $faker->randomElement($quotes),
        'birth_country'   => $faker->randomElement($countries),
        'current_country' => $faker->randomElement($countries)
    ];
});
