<?php

return [
    "Adidas",
    "Adidas Originals",
    "Afends",
    "Affliction",
    "Alo",
    "Alpinestars",
    "AND1",
    "Asics",
    "Assos",
    "Arena",
    "Armada",
    "Athleta",
    "Atomic",
    "Audi",
    "Babolat",
    "Banana Moon",
    "Bauer",
    "Beach Bunny",
    "Benetton",
    "Beyond Yoga",
    "Bianchi",
    "Billabong",
    "Bjorn Borg",
    "Black Diamond",
    "BMC",
    "BMW",
    "Body Glove",
    "Boss Green",
    "Brooks",
    "Burton",
    "Callaway",
    "Calvin Klein",
    "Canada Goose",
    "Cannondale",
    "Canterbury",
    "Canyon",
    "Carhartt",
    "Carrera",
    "Cervelo",
    "Champion",
    "Colnago",
    "Columbia",
    "Converse",
    "Cressi",
    "Crocs",
    "Cruyff",
    "Cube",
    "Dainese",
    "DC",
    "Deus",
    "DGK",
    "Diadora",
    "Dickies",
    "Ducati",
    "DVS",
    "EA7",
    "Easton",
    "Eastpak",
    "Ecco",
    "Element",
    "Ellesse",
    "Esprit",
    "Everlast",
    "Fabletics",
    "Ferrari",
    "Fila",
    "Fischer",
    "Fitbikeco",
    "Fitbit",
    "Franklin & Marshall",
    "Fred Perry",
    "Fruit of the Loom",
    "Gaastra",
    "Gap",
    "Geox",
    "Giant",
    "Globe",
    "Gola",
    "GoPro",
    "GT",
    "Haro",
    "Havaianas",
    "Hayabusa",
    "Head",
    "Heelys",
    "Helly Hansen",
    "Herschel",
    "Hi-Tec",
    "Hoka One One",
    "Honda",
    "HUF",
    "Hummel",
    "Hunkemoller",
    "Hurley",
    "Ivivva",
    "Ivy Park",
    "Jack Wolfskin",
    "Joma",
    "Jordan",
    "Just Cavalli",
    "K2",
    "K-Swiss",
    "Kappa",
    "Lacoste",
    "Lamborghini",
    "La Sportiva",
    "Le coq sportif",
    "Lee Cooper",
    "Levi's",
    "Line",
    "Li-Ning",
    "Lole",
    "Lorna Jane",
    "Lotto",
    "Loudmouth",
    "Louisville Slugger",
    "Lululemon",
    "Macbeth",
    "Mambo",
    "Mammut",
    "Marc O'Polo",
    "Mares",
    "Maserati",
    "McDavid",
    "Mercedes",
    "Merida",
    "Mika",
    "Mikasa",
    "Mitchell & Ness",
    "Mizuno",
    "Molten",
    "Moncler",
    "Munich",
    "Nautica",
    "New Balance",
    "New Era",
    "Nixon",
    "Nike",
    "Nike SB",
    "Oakley",
    "Obey",
    "Oiselle",
    "Old Navy",
    "Olympikus",
    "Omega",
    "O'Neill",
    "Only",
    "Onzie",
    "Orbea",
    "Pantofola d'Oro",
    "Patagonia",
    "Peak Performance",
    "Penalty",
    "Pinarello",
    "Pirma",
    "Polar",
    "Pony",
    "Porsche",
    "Prada",
    "Puma",
    "Quechua",
    "Quicksilver",
    "RVCA",
    "Ralph Lauren",
    "Rapha",
    "Rawlings",
    "Ray-Ban",
    "Reebok",
    "Reebok Classic",
    "Reef",
    "Regatta",
    "Ridley",
    "Rip Curl",
    "Roberto Cavalli",
    "Rossignol",
    "Roxy",
    "Salomon",
    "Santa Cruz",
    "Santini",
    "Sanuk",
    "Saucony",
    "Scarpa",
    "Scott",
    "Scubapro",
    "Seafolly",
    "Senda",
    "Shimano",
    "Sism",
    "Shock Doctor",
    "Skechers",
    "Skins",
    "Slazenger",
    "S Oliver",
    "Spalding",
    "Speedo",
    "Specialized",
    "Stance",
    "Starter",
    "Stella McCartney",
    "Steve Madden",
    "Stussy",
    "Subrosa",
    "Superdry",
    "Superga",
    "Suzuki",
    "Sweaty Betty",
    "Tapout",
    "TaylorMade",
    "The North Face",
    "Thrasher",
    "Timberland",
    "Titleist",
    "Tommy Hilfiger",
    "Topper",
    "Trek",
    "Triumph",
    "TYR",
    "Umbro",
    "Under Armour",
    "Vans",
    "Victoria Sport",
    "Venum",
    "Vespa",
    "Volcom",
    "Volkl",
    "Wilson",
    "Woolrich",
    "WTP",
    "Yamaha",
    "Yeti",
    "Yonex",
];
